name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: checkboxes
    id: search-check
    attributes:
      label: Before submitting
      options:
        - label: I have searched for existing feature requests
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: A clear description of what you'd like to see added
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      placeholder: Why would this feature be useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Any additional context
      placeholder: Screenshots, mockups, or other context
